Add colors and improve messages

diff --git a/assemble/bin/accumulo-cluster b/assemble/bin/accumulo-cluster
--- a/assemble/bin/accumulo-cluster
+++ b/assemble/bin/accumulo-cluster
@@ -28,50 +28,75 @@
 
 function print_usage() {
   cat <<EOF
-Usage: accumulo-cluster <command> [<option> ...]
+$(cyan Usage): $(green accumulo-cluster) <$(yellow command)> [<$(yellow option)> ...]
 
-Options:
-  General options:
-    --dry-run                Prints information and commands, but does not execute them
-    --local                  Operates on matching local services only (no SSH)
+$(cyan Options):
+  $(cyan General options):
+    $(green --dry-run)                Prints information and commands, but does not execute them
+    $(green --local)                  Operates on matching local services only (no SSH)
 
-  Service type selection options (if none are used, all service types are selected):
-    --manager                Selects the manager service (oversees cluster operations)
-    --gc                     Selects the gc service (cleans up unused files)
-    --monitor                Selects the monitor web service (shows cluster information)
-    --compaction-coordinator Selects the compaction-coordinator service (external compactions)
-    --tservers               Selects the tablet server services (read/write operations on tablets)
-    --sservers[=group]       Selects the scan server services (read-only eventually consistent scans)
-    --compactors[=group]     Selects the compactor services (external compactions)
-    --no-tservers            Deprecated. Selects service types except tservers (for backwards compatibility)
+  $(cyan 'Service type selection options (if none are used, all service types are selected)'):
+    $(yellow NOTE): some commands support optionally selecting only a specific group or groups for
+          that service. To select multiple groups, separate the groups by spaces in quotes.
 
-Commands:
-  create-config              Creates cluster config (ignores service selection options)
-  start                      Starts Accumulo cluster services
-  stop                       Stops Accumulo cluster services
-  restart                    Restarts Accumulo cluster services
-  kill                       Kills Accumulo cluster services
+    $(green --manager)                Selects the manager service (oversees cluster operations)
+    $(green --gc)                     Selects the gc service (cleans up unused files)
+    $(green --monitor)                Selects the monitor web service (shows cluster information)
+    $(green --compaction-coordinator) Selects the compaction-coordinator service (external compactions)
+    $(green --tservers)               Selects the tablet server services (read/write operations on tablets)
+    $(green --sservers)[$(yellow =group)]       Selects the scan server services (read-only eventually consistent scans)
+    $(green --compactors)[$(yellow =group)]     Selects the compactor services (external compactions)
+    $(green --no-tservers)            $(yellow Deprecated). Selects service types except tservers (for backwards compatibility)
 
-  Deprecated commands:
-    start-non-tservers       Deprecated. Alias for "start --no-tservers"
-    start-servers            Deprecated. Alias for "start"
-    stop-servers             Deprecated. Alias for "stop"
-    start-tservers           Deprecated. Alias for "start --tservers"
-    stop-tservers            Deprecated. Alias for "stop --tservers"
-    start-here               Deprecated. Alias for "start --local"
-    stop-here                Deprecated. Alias for "stop --local"
+$(cyan Commands):
+  $(green create-config)              Creates cluster config (ignores service selection options)
+  $(green start)                      Starts Accumulo cluster services
+  $(green stop)                       Stops Accumulo cluster services
+  $(green restart)                    Restarts Accumulo cluster services
+  $(green kill)                       Kills Accumulo cluster services
 
-Examples:
-  accumulo-cluster start                              # start all servers
-  accumulo-cluster start --dry-run                    # print debug information and commands to be executed
-  accumulo-cluster start --local                      # start all local services
-  accumulo-cluster start --local --manager            # start local manager services
-  accumulo-cluster start --tservers                   # start all tservers
-  accumulo-cluster start --sservers=group1            # start all group1 sservers
-  accumulo-cluster start --local --manager --tservers # Start the local manager and local tservers
+  $(cyan Deprecated commands):
+    $(green start-non-tservers)       $(yellow Deprecated). Alias for "start --no-tservers"
+    $(green start-servers)            $(yellow Deprecated). Alias for "start"
+    $(green stop-servers)             $(yellow Deprecated). Alias for "stop"
+    $(green start-tservers)           $(yellow Deprecated). Alias for "start --tservers"
+    $(green stop-tservers)            $(yellow Deprecated). Alias for "stop --tservers"
+    $(green start-here)               $(yellow Deprecated). Alias for "start --local"
+    $(green stop-here)                $(yellow Deprecated). Alias for "stop --local"
+
+$(cyan Examples):
+  $(purple accumulo-cluster start)                              $(blue '# start all servers')
+  $(purple accumulo-cluster start --dry-run)                    $(blue '# print debug information and commands to be executed')
+  $(purple accumulo-cluster start --local)                      $(blue '# start all local services')
+  $(purple accumulo-cluster start --local --manager)            $(blue '# start local manager services')
+  $(purple accumulo-cluster start --tservers)                   $(blue '# start all tservers')
+  $(purple accumulo-cluster start --sservers=group1)            $(blue '# start all group1 sservers')
+  $(purple accumulo-cluster start --sservers=\"group1 group2\")   $(blue '# start all group1 and group2 sservers')
+  $(purple accumulo-cluster start --local --manager --tservers) $(blue '# Start the local manager and local tservers')
 
 EOF
 }
+
+function checkTerminalSupportsColor() {
+  local c
+  # get the number of colors supported
+  c=$(tput colors 2>/dev/null) || c=-1
+  # if STDOUT is a terminal and the number of colors is at least 8
+  [[ -t 1 && $c -ge 8 ]]
+}
+
+function colorize() {
+  local c=$1
+  shift
+  [[ $COLOR_ENABLED == 1 ]] && echo -e "\\e[0;${c}m${*}\\e[0m" || echo "$@"
+}
+function red() { colorize 31 "$@"; }
+function green() { colorize 32 "$@"; }
+function yellow() { colorize 33 "$@"; }
+function blue() { colorize 34 "$@"; }
+function purple() { colorize 35 "$@"; }
+function cyan() { colorize 36 "$@"; }
+function white() { colorize 37 "$@"; }
 
 function parse_args() {
   local originalArgs=("$@")
@@ -93,7 +118,7 @@ function parse_args() {
   # the correct version of getopt will always exit with exit code 4 when provided the `-T` flag
   getopt -T &>/dev/null
   if (($? != 4)); then
-    echo 'Missing util-linux (or equivalent) version of getopt. Unable to continue.'
+    echo "$(red ERROR): Missing $(yellow util-linux) (or equivalent) version of $(green getopt). Unable to continue."
     exit 2
   fi
 
@@ -158,7 +183,7 @@ function parse_args() {
         shift 2
         ;;
       --no-tservers)
-        echo "The --no-tservers option is deprecated. Please specify the servers you wish to manage instead"
+        echo "$(yellow WARN): The $(yellow "--no-tservers") option is deprecated. Please specify the servers you wish to manage instead"
         ARG_ALL=0
         ARG_MANAGER=1
         ARG_GC=1
@@ -173,7 +198,7 @@ function parse_args() {
         break
         ;;
       *)
-        echo "Unhandled option: $1"
+        echo "$(red ERROR): Unhandled option: $(yellow "$1")"
         print_usage
         exit 1
         ;;
@@ -186,7 +211,7 @@ function parse_args() {
     # use getopt to display the remaining non-option parameters quoted for readability
     local remaining
     remaining="$(getopt -o "" -- "$@")"
-    invalid_args "Only one <command> is allowed, but found:${remaining#*--}"
+    invalid_args "Only one <$(yellow command)> is allowed, but found:$(yellow "${remaining#*--}")"
   fi
   ARG_CMD=$1
   debug "ARG_CMD=$ARG_CMD"
@@ -206,14 +231,14 @@ function parse_args() {
 }
 
 function invalid_args() {
-  echo "Invalid arguments: $*"
+  echo "$(red ERROR): $(yellow invalid arguments): $*"
   echo
   print_usage 1>&2
   exit 1
 }
 
 function parse_fail() {
-  echo "Failed to parse $conf/cluster.yaml"
+  echo "$(red ERROR): Failed to parse $(yellow "$conf/cluster.yaml")"
   exit 1
 }
 
@@ -223,7 +248,7 @@ function isDebug() {
 
 # if debug is on, print and return true; otherwise, return false
 function debug() {
-  isDebug && echo "DEBUG: $*"
+  isDebug && echo "$(blue DEBUG): $(cyan "$*")"
 }
 
 function quote() {
@@ -236,7 +261,7 @@ function quote() {
   quoted=$(POSIXLY_CORRECT=1 getopt -o "" -- '' "$@") &&
     [[ $quoted =~ ^[[:space:]]*--[[:space:]]*\'\'[[:space:]]*(.*)$ ]] && echo "${BASH_REMATCH[1]}" &&
     return
-  echo "Script error - unable to quote: $*"
+  echo "$(red ERROR): $(yellow internal script error): unable to quote: $(yellow "$*")"
   exit 1
 }
 
@@ -253,7 +278,7 @@ function canRunOnHost() {
   fi
 
   if [[ -z $1 ]]; then
-    echo "Host argument expected"
+    echo "$(red ERROR): Host argument expected but missing"
     exit 1
   fi
 
@@ -272,8 +297,9 @@ function parse_config() {
 
   for file in slaves tservers monitor tracers gc managers masters; do
     if [[ -f $conf/$file ]]; then
-      echo "ERROR: A '$file' file was found in $conf/"
-      echo "Accumulo now uses cluster host configuration information from 'cluster.yaml' and requires that the '$file' file not be present to reduce confusion."
+      echo "$(red ERROR): A $(yellow "$file") file was found in $(yellow "$conf/")"
+      echo "$(red ERROR): Accumulo now uses cluster host configuration information from $(yellow cluster.yaml)"
+      echo "$(red ERROR): and requires that the $(yellow "$file") file not be present to reduce confusion."
       exit 1
     fi
   done
@@ -284,8 +310,9 @@ function parse_config() {
   local G
 
   if [[ ! -f $conf/cluster.yaml ]]; then
-    echo "ERROR: A 'cluster.yaml' file was not found at $conf/cluster.yaml"
-    echo "Please make sure it exists and is configured with the host information. Run 'accumulo-cluster create-config' to create an example configuration."
+    echo "$(red ERROR): File not found $(yellow "$conf/cluster.yaml")"
+    echo "$(red ERROR): Please make sure it exists and is configured with the host information."
+    echo "$(red ERROR): Run $(yellow accumulo-cluster create-config) to create an example configuration."
     exit 1
   fi
 
@@ -294,11 +321,18 @@ function parse_config() {
   "$accumulo_cmd" org.apache.accumulo.core.conf.cluster.ClusterConfigParser "$conf/cluster.yaml" "$CONFIG_FILE" || parse_fail
   #shellcheck source=/dev/null
   . "$CONFIG_FILE"
-  debug "Parsed config:" && cat "$CONFIG_FILE"
+  debug "Parsed config from $(white "$conf/cluster.yaml")"
+  local line
+  if isDebug; then
+    while read -r line; do
+      debug "$(white "$line")"
+    done <"$CONFIG_FILE"
+  fi
   rm -f "$CONFIG_FILE"
 
+  # this might not be possible, since the ClusterConfigParser would probably fail instead
   if [[ -z $MANAGER_HOSTS ]]; then
-    echo "ERROR: managers not found in $conf/cluster.yaml"
+    echo "$(red ERROR): $(yellow managers) not found in $(yellow "$conf/cluster.yaml")"
     exit 1
   fi
 
@@ -335,7 +369,7 @@ function parse_config() {
 
   # This version requires a compaction coordinator for compactors
   if [[ -n $COMPACTOR_GROUPS && -z $COORDINATOR_HOSTS ]]; then
-    echo "WARN: External compactor group configured, but no coordinator configured"
+    echo "$(yellow WARN): External compactor group(s) configured, but no coordinator configured"
   fi
 
   if [[ -z $COMPACTOR_GROUPS ]]; then
@@ -345,19 +379,19 @@ function parse_config() {
     for group in $COMPACTOR_GROUPS; do
       G="COMPACTOR_HOSTS_$group"
       if [[ -z ${!G} ]]; then
-        echo "WARN: External compactor group $group configured, but no compactors configured for it"
+        echo "$(yellow WARN): External compactor group $(yellow "$group") configured, but no compactors configured for it"
       fi
     done
   fi
 
   tservers_found="false"
   if [[ -z $TSERVER_GROUPS ]]; then
-    echo "WARN: No tablet server groups configured"
+    echo "$(yellow WARN): No tablet server groups configured"
   else
     for group in $TSERVER_GROUPS; do
       G="TSERVER_HOSTS_$group"
       if [[ -z ${!G} ]]; then
-        echo "WARN: tablet server group $group configured, but no hosts configured for it"
+        echo "$(yellow WARN): tablet server group $(yellow "$group") configured, but no hosts configured for it"
       else
         tservers_found="true"
       fi
@@ -365,7 +399,7 @@ function parse_config() {
   fi
 
   if [[ $tservers_found != "true" ]]; then
-    echo "ERROR: There are no tablet servers configured, Accumulo requires at least 1 tablets server to host system tables"
+    echo "$(red ERROR): There are no tablet servers configured, Accumulo requires at least $(yellow 1) tablets server to host system tables"
     exit 1
   fi
 
@@ -373,7 +407,7 @@ function parse_config() {
     for group in $SSERVER_GROUPS; do
       G="SSERVER_HOSTS_$group"
       if [[ -z ${!G} ]]; then
-        echo "WARN: scan server group $group configured, but no hosts configured for it"
+        echo "$(yellow WARN): scan server group $(yellow "$group") configured, but no hosts configured for it"
       fi
     done
   fi
@@ -381,12 +415,12 @@ function parse_config() {
   manager1=$(echo "$MANAGER_HOSTS" | cut -d" " -f1)
 
   if [[ -z $MONITOR_HOSTS ]]; then
-    echo "WARN: monitors not found in $conf/cluster.yaml, using first manager host $manager1"
+    echo "$(yellow WARN): monitors not found in $(yellow "$conf/cluster.yaml"), using first manager host $(green "$manager1")"
     MONITOR_HOSTS=$manager1
   fi
 
   if [[ -z $GC_HOSTS ]]; then
-    echo "WARN: gc not found in $conf/cluster.yaml, using first manager host $manager1"
+    echo "$(yellow WARN): gc not found in $(yellow "$conf/cluster.yaml"), using first manager host $(green "$manager1")"
     GC_HOSTS=$manager1
   fi
 
@@ -430,10 +464,8 @@ function control_services() {
   unset DISPLAY
   local operation=$1
 
-  if [[ $operation != "start" &&
-    $operation != "stop" &&
-    $operation != "kill" ]]; then
-    echo "Invalid operation: $operation"
+  if [[ $operation != "start" && $operation != "stop" && $operation != "kill" ]]; then
+    echo "$(red ERROR): Invalid operation: $(yellow "$operation")"
     exit 1
   fi
 
@@ -487,12 +519,18 @@ function control_services() {
       tserver_groups=$ARG_TSERVER_GROUP
     fi
     for group in $tserver_groups; do
-      echo "Executing '$ARG_CMD' on tablet servers for group '$group'"
-      count=1
+      local msg
+      local msgNoColor
+      local msgLen
+      msg="Executing $(green "$ARG_CMD") on $(purple tablet servers) for group $(yellow "$group") ..."
+      msgNoColor=$(echo "$msg" | sed -e $'s/\x1b\[[0-9;]*m//g')
+      count=${#msgNoColor}
+      (( count > 71 )) && count=69 # only print up to 3 more dots if the line is too long
+      echo -n "$msg"
       hosts="TSERVER_HOSTS_$group"
       for tserver in ${!hosts}; do
         if canRunOnHost "$tserver"; then
-          isDebug || echo -n "."
+          echo -n "."
           execute_command "$operation" "$tserver" tserver "$group"
           if ((++count % 72 == 0)); then
             echo
@@ -508,6 +546,7 @@ function control_services() {
   if [[ $ARG_ALL == 1 || $ARG_MANAGER == 1 ]]; then
     for manager in $MANAGER_HOSTS; do
       if canRunOnHost "$manager"; then
+        echo "Executing $(green "$ARG_CMD") on $(purple managers)"
         execute_command "$operation" "$manager" manager "default"
       fi
     done
@@ -517,6 +556,7 @@ function control_services() {
   if [[ $ARG_ALL == 1 || $ARG_GC == 1 ]]; then
     for gc in $GC_HOSTS; do
       if canRunOnHost "$gc"; then
+        echo "Executing $(green "$ARG_CMD") on $(purple garbage collectors)"
         execute_command "$operation" "$gc" gc "default"
       fi
     done
@@ -526,6 +566,7 @@ function control_services() {
   if [[ $ARG_ALL == 1 || $ARG_MONITOR == 1 ]]; then
     for monitor in $MONITOR_HOSTS; do
       if canRunOnHost "$monitor"; then
+        echo "Executing $(green "$ARG_CMD") on $(purple monitors)"
         execute_command "$operation" "$monitor" monitor "default"
       fi
     done
@@ -535,6 +576,7 @@ function control_services() {
   if [[ $ARG_ALL == 1 || $ARG_COORDINATOR == 1 ]]; then
     for coordinator in $COORDINATOR_HOSTS; do
       if canRunOnHost "$coordinator"; then
+        echo "Executing $(green "$ARG_CMD") on $(purple compaction coordinators)"
         execute_command "$operation" "$coordinator" compaction-coordinator "default"
       fi
     done
@@ -548,7 +590,7 @@ function control_services() {
       sserver_groups=$ARG_SSERVER_GROUP
     fi
     for group in $sserver_groups; do
-      echo "Executing '$ARG_CMD' on scan servers for group named '$group'"
+      echo "Executing $(green "$ARG_CMD") on $(purple scan servers) for group $(yellow "$group")"
       hosts="SSERVER_HOSTS_$group"
       for sserver in ${!hosts}; do
         if canRunOnHost "$sserver"; then
@@ -566,7 +608,7 @@ function control_services() {
       compactor_groups=$ARG_COMPACTOR_GROUP
     fi
     for group in $compactor_groups; do
-      echo "Executing '$ARG_CMD' on compactors for group named '$group'"
+      echo "Executing $(green "$ARG_CMD") on $(purple compactors) for group $(yellow "$group")"
       hosts="COMPACTOR_HOSTS_$group"
       for compactor in ${!hosts}; do
         if canRunOnHost "$compactor"; then
@@ -587,6 +629,7 @@ function control_services() {
 
 function main() {
 
+  checkTerminalSupportsColor && COLOR_ENABLED=1 || COLOR_ENABLED=0
   parse_args "$@"
 
   # Resolve base directory
@@ -605,7 +648,7 @@ function main() {
   SSH=('ssh' '-qnf' '-o' 'ConnectTimeout=2')
 
   mapfile -t LOCAL_HOST_ADDRESSES < <(get_localhost_addresses)
-  isDebug && echo "DEBUG: LOCAL_HOST_ADDRESSES=${LOCAL_HOST_ADDRESSES[*]}"
+  debug "LOCAL_HOST_ADDRESSES=${LOCAL_HOST_ADDRESSES[*]}"
 
   case "$ARG_CMD" in
     create-config)
