ACCUMULO-4612 Simplify Accumulo memory configuration
* The MEMORY property type now supports percentage of max JVM memory
  for settings. Several properties now use percentage for default which
  allow default to work for various memory environments.
* Created new BYTES property type which only supports fixed memory
* Removed 'accumulo create-config' command as it no longer needed.
* Removed default classpath settings from 'general.classpaths' property
  in accumulo-site.xml and deprecated property. Users can now configure
  CLASSPATH variable in accumulo-env.sh.

diff --git a/assemble/bin/accumulo-util b/assemble/bin/accumulo-util
--- a/assemble/bin/accumulo-util
+++ b/assemble/bin/accumulo-util
@@ -20,7 +20,6 @@ function print_usage {
 Usage: accumulo-util <command> (<argument> ...)
 
 Commands:
-  create-config       Creates Accumulo configuration
   build-native        Builds Accumulo native libraries
   hadoop-jar          Runs 'hadoop jar' command with Accumulo jars
   gen-monitor-cert    Generates Accumulo monitor certficate
@@ -28,386 +27,6 @@ Commands:
   
 EOF
   exit 1
-}
-
-function create_config_usage() {
-  cat <<EOF
-Usage: accumulo-util create-config [-options]
-where options include (long options not available on all platforms):
-    -d, --dir        Alternate directory to setup config files
-    -s, --size       Supported sizes: '1GB' '2GB' '3GB' '512MB'
-    -n, --native     Configure to use native libraries
-    -j, --jvm        Configure to use the jvm
-    -o, --overwrite  Overwrite the default config directory
-    -v, --version    Specify the Apache Hadoop version supported versions: '1' '2'
-    -k, --kerberos   Configure for use with Kerberos
-    -h, --help       Print this help message
-EOF
-}
-
-function create_config() {
-  TEMPLATE_CONF_DIR="${conf}/templates"
-  CONF_DIR="${conf}"
-  ACCUMULO_SITE=accumulo-site.xml
-  ACCUMULO_ENV=accumulo-env.sh
-
-  SIZE=
-  TYPE=
-  HADOOP_VERSION=
-  OVERWRITE="0"
-  BASE_DIR=
-  KERBEROS=
-
-  #Execute getopt
-  if [[ $(uname -s) == "Linux" ]]; then
-    args=$(getopt -o "b:d:s:njokv:h" -l "basedir:,dir:,size:,native,jvm,overwrite,kerberos,version:,help" -q -- "$@")
-  else # Darwin, BSD
-    args=$(getopt b:d:s:njokv:h "$@")
-  fi
-
-  #Bad arguments
-  if [[ $? != 0 ]]; then
-    create_config_usage 1>&2
-    exit 1
-  fi
-  eval set -- "${args[@]}"
-
-  for i
-  do
-    case "$i" in
-      -b|--basedir) #Hidden option used to set general.maven.project.basedir for developers
-        BASE_DIR=$2; shift
-        shift;;
-      -d|--dir)
-        CONF_DIR=$2; shift
-        shift;;
-      -s|--size)
-        SIZE=$2; shift
-        shift;;
-      -n|--native)
-        TYPE=native
-        shift;;
-      -j|--jvm)
-        TYPE=jvm
-        shift;;
-      -o|--overwrite)
-        OVERWRITE=1
-        shift;;
-      -v|--version)
-        HADOOP_VERSION=$2; shift
-        shift;;
-      -k|--kerberos)
-        KERBEROS="true"
-        shift;;
-      -h|--help)
-        create_config_usage
-        exit 0
-        shift;;
-      --)
-        shift
-        break;;
-    esac
-  done
-
-  while [[ "${OVERWRITE}" = "0" ]]; do
-    if [[ -e "${CONF_DIR}/${ACCUMULO_ENV}" || -e "${CONF_DIR}/${ACCUMULO_SITE}" ]]; then
-      echo "Warning your current config files in ${CONF_DIR} will be overwritten!"
-      echo
-      echo "How would you like to proceed?:"
-      select CHOICE in 'Continue with overwrite' 'Specify new conf dir'; do
-        if [[ "${CHOICE}" = 'Specify new conf dir' ]]; then
-          echo -n "Please specifiy new conf directory: "
-          read CONF_DIR
-        elif [[ "${CHOICE}" = 'Continue with overwrite' ]]; then
-          OVERWRITE=1
-        fi
-        break
-      done
-    else
-      OVERWRITE=1
-    fi
-  done
-  echo "Copying configuration files to: ${CONF_DIR}"
-
-  #Native 1GB
-  native_1GB_tServer="'-Xmx128m' '-Xms128m'"
-  _1GB_master="'-Xmx128m' '-Xms128m'"
-  _1GB_monitor="'-Xmx64m' '-Xms64m'"
-  _1GB_gc="'-Xmx64m' '-Xms64m'"
-  _1GB_other="'-Xmx128m' '-Xms64m'"
-  _1GB_shell="${_1GB_other}"
-
-  _1GB_memoryMapMax="256M"
-  native_1GB_nativeEnabled="true"
-  _1GB_cacheDataSize="15M"
-  _1GB_cacheIndexSize="40M"
-  _1GB_sortBufferSize="50M"
-  _1GB_waLogMaxSize="256M"
-
-  #Native 2GB
-  native_2GB_tServer="'-Xmx256m' '-Xms256m'"
-  _2GB_master="'-Xmx256m' '-Xms256m'"
-  _2GB_monitor="'-Xmx128m' '-Xms64m'"
-  _2GB_gc="'-Xmx128m' '-Xms128m'"
-  _2GB_other="'-Xmx256m' '-Xms64m'"
-  _2GB_shell="${_2GB_other}"
-
-  _2GB_memoryMapMax="512M"
-  native_2GB_nativeEnabled="true"
-  _2GB_cacheDataSize="30M"
-  _2GB_cacheIndexSize="80M"
-  _2GB_sortBufferSize="50M"
-  _2GB_waLogMaxSize="512M"
-
-  #Native 3GB
-  native_3GB_tServer="'-Xmx1g' '-Xms1g' '-XX:NewSize=500m' '-XX:MaxNewSize=500m'"
-  _3GB_master="'-Xmx1g' '-Xms1g'"
-  _3GB_monitor="'-Xmx1g' '-Xms256m'"
-  _3GB_gc="'-Xmx256m' '-Xms256m'"
-  _3GB_other="'-Xmx1g' '-Xms256m'"
-  _3GB_shell="${_3GB_other}"
-
-  _3GB_memoryMapMax="1G"
-  native_3GB_nativeEnabled="true"
-  _3GB_cacheDataSize="128M"
-  _3GB_cacheIndexSize="128M"
-  _3GB_sortBufferSize="200M"
-  _3GB_waLogMaxSize="1G"
-
-  #Native 512MB
-  native_512MB_tServer="'-Xmx48m' '-Xms48m'"
-  _512MB_master="'-Xmx128m' '-Xms128m'"
-  _512MB_monitor="'-Xmx64m' '-Xms64m'"
-  _512MB_gc="'-Xmx64m' '-Xms64m'"
-  _512MB_other="'-Xmx128m' '-Xms64m'"
-  _512MB_shell="${_512MB_other}"
-
-  _512MB_memoryMapMax="80M"
-  native_512MB_nativeEnabled="true"
-  _512MB_cacheDataSize="7M"
-  _512MB_cacheIndexSize="20M"
-  _512MB_sortBufferSize="50M"
-  _512MB_waLogMaxSize="100M"
-
-  #JVM 1GB
-  jvm_1GB_tServer="'-Xmx384m' '-Xms384m'"
-
-  jvm_1GB_nativeEnabled="false"
-
-  #JVM 2GB
-  jvm_2GB_tServer="'-Xmx768m' '-Xms768m'"
-
-  jvm_2GB_nativeEnabled="false"
-
-  #JVM 3GB
-  jvm_3GB_tServer="'-Xmx2g' '-Xms2g' '-XX:NewSize=1G' '-XX:MaxNewSize=1G'"
-
-  jvm_3GB_nativeEnabled="false"
-
-  #JVM 512MB
-  jvm_512MB_tServer="'-Xmx128m' '-Xms128m'"
-
-  jvm_512MB_nativeEnabled="false"
-
-
-  if [[ -z "${SIZE}" ]]; then
-    echo "Choose the heap configuration:"
-    select DIRNAME in 1GB 2GB 3GB 512MB; do
-      echo "Using '${DIRNAME}' configuration"
-      SIZE=${DIRNAME}
-      break
-    done
-  elif [[ "${SIZE}" != "1GB" && "${SIZE}" != "2GB"  && "${SIZE}" != "3GB" && "${SIZE}" != "512MB" ]]; then
-    echo "Invalid memory size"
-    echo "Supported sizes: '1GB' '2GB' '3GB' '512MB'"
-    exit 1
-  fi
-
-  if [[ -z "${TYPE}" ]]; then
-    echo
-    echo "Choose the Accumulo memory-map type:"
-    select TYPENAME in Java Native; do
-      if [[ "${TYPENAME}" == "Native" ]]; then
-        TYPE="native"
-        echo "Don't forget to build the native libraries using the command 'accumulo-util build-native'"
-      elif [[ "${TYPENAME}" == "Java" ]]; then
-        TYPE="jvm"
-      fi
-      echo "Using '${TYPE}' configuration"
-      echo
-      break
-    done
-  fi
-
-  if [[ -z "${HADOOP_VERSION}" ]]; then
-    echo
-    echo "Choose the Apache Hadoop version:"
-    select HADOOP in 'Hadoop 2' 'HDP 2.0/2.1' 'HDP 2.2' 'IOP 4.1'; do
-      if [ "${HADOOP}" == "Hadoop 2" ]; then
-        HADOOP_VERSION="2"
-      elif [ "${HADOOP}" == "HDP 2.0/2.1" ]; then
-        HADOOP_VERSION="HDP2"
-      elif [ "${HADOOP}" == "HDP 2.2" ]; then
-        HADOOP_VERSION="HDP2.2"
-      elif [ "${HADOOP}" == "IOP 4.1" ]; then
-        HADOOP_VERSION="IOP4.1"
-      fi
-      echo "Using Hadoop version '${HADOOP_VERSION}' configuration"
-      echo
-      break
-    done
-  elif [[ "${HADOOP_VERSION}" != "2" && "${HADOOP_VERSION}" != "HDP2" && "${HADOOP_VERSION}" != "HDP2.2" ]]; then
-    echo "Invalid Hadoop version"
-    echo "Supported Hadoop versions: '2', 'HDP2', 'HDP2.2'"
-    exit 1
-  fi
-
-  TRACE_USER="root"
-
-  if [[ ! -z "${KERBEROS}" ]]; then
-    echo
-    read -p "Enter server's Kerberos principal: " PRINCIPAL
-    read -p "Enter server's Kerberos keytab: " KEYTAB
-    TRACE_USER="${PRINCIPAL}"
-  fi
-
-  for var in SIZE TYPE HADOOP_VERSION; do
-    if [[ -z ${!var} ]]; then
-      echo "Invalid $var configuration"
-      exit 1
-    fi
-  done
-
-  TSERVER="${TYPE}_${SIZE}_tServer"
-  MASTER="_${SIZE}_master"
-  MONITOR="_${SIZE}_monitor"
-  GC="_${SIZE}_gc"
-  SHELL="_${SIZE}_shell"
-  OTHER="_${SIZE}_other"
-
-  MEMORY_MAP_MAX="_${SIZE}_memoryMapMax"
-  NATIVE="${TYPE}_${SIZE}_nativeEnabled"
-  CACHE_DATA_SIZE="_${SIZE}_cacheDataSize"
-  CACHE_INDEX_SIZE="_${SIZE}_cacheIndexSize"
-  SORT_BUFFER_SIZE="_${SIZE}_sortBufferSize"
-  WAL_MAX_SIZE="_${SIZE}_waLogMaxSize"
-
-  MAVEN_PROJ_BASEDIR=""
-
-  if [[ ! -z "${BASE_DIR}" ]]; then
-    MAVEN_PROJ_BASEDIR="\n  <property>\n    <name>general.maven.project.basedir</name>\n    <value>${BASE_DIR}</value>\n  </property>\n"
-  fi
-
-  mkdir -p "${CONF_DIR}" && cp "${TEMPLATE_CONF_DIR}"/{$ACCUMULO_SITE,$ACCUMULO_ENV} "${CONF_DIR}"/
-
-  #Configure accumulo-env.sh
-  sed -e "s/\${tServerHigh_tServerLow}/${!TSERVER}/" \
-    -e "s/\${masterHigh_masterLow}/${!MASTER}/" \
-    -e "s/\${monitorHigh_monitorLow}/${!MONITOR}/" \
-    -e "s/\${gcHigh_gcLow}/${!GC}/" \
-    -e "s/\${shellHigh_shellLow}/${!SHELL}/" \
-    -e "s/\${otherHigh_otherLow}/${!OTHER}/" \
-    "${TEMPLATE_CONF_DIR}/$ACCUMULO_ENV" > "${CONF_DIR}/$ACCUMULO_ENV"
-
-  #Configure accumulo-site.xml
-  sed -e "s/\${memMapMax}/${!MEMORY_MAP_MAX}/" \
-    -e "s/\${nativeEnabled}/${!NATIVE}/" \
-    -e "s/\${cacheDataSize}/${!CACHE_DATA_SIZE}/" \
-    -e "s/\${cacheIndexSize}/${!CACHE_INDEX_SIZE}/" \
-    -e "s/\${sortBufferSize}/${!SORT_BUFFER_SIZE}/" \
-    -e "s/\${waLogMaxSize}/${!WAL_MAX_SIZE}/" \
-    -e "s=\${traceUser}=${TRACE_USER}=" \
-    -e "s=\${mvnProjBaseDir}=${MAVEN_PROJ_BASEDIR}=" "${TEMPLATE_CONF_DIR}/$ACCUMULO_SITE" > "${CONF_DIR}/$ACCUMULO_SITE"
-
-  # If we're not using kerberos, filter out the krb properties
-  if [[ -z "${KERBEROS}" ]]; then
-    sed -e 's/<!-- Kerberos requirements -->/<!-- Kerberos requirements --><!--/' \
-      -e 's/<!-- End Kerberos requirements -->/--><!-- End Kerberos requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-  else
-    # Make the substitutions
-    sed -e "s!\${keytab}!${KEYTAB}!" \
-      -e "s!\${principal}!${PRINCIPAL}!" \
-      "${CONF_DIR}/${ACCUMULO_SITE}" > temp
-    mv temp "${CONF_DIR}/${ACCUMULO_SITE}"
-  fi
-
-  # Configure hadoop version
-  if [[ "${HADOOP_VERSION}" == "2" ]]; then
-    sed -e 's/<!-- HDP 2.0 requirements -->/<!-- HDP 2.0 requirements --><!--/' \
-      -e 's/<!-- End HDP 2.0 requirements -->/--><!-- End HDP 2.0 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- HDP 2.2 requirements -->/<!-- HDP 2.2 requirements --><!--/' \
-      -e 's/<!-- End HDP 2.2 requirements -->/--><!-- End HDP 2.2 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- IOP 4.1 requirements -->/<!-- IOP 4.1 requirements --><!--/' \
-      -e 's/<!-- End IOP 4.1 requirements -->/--><!-- End IOP 4.1 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-  elif [[ "${HADOOP_VERSION}" == "HDP2" ]]; then
-    sed -e 's/<!-- Hadoop 2 requirements -->/<!-- Hadoop 2 requirements --><!--/' \
-      -e 's/<!-- End Hadoop 2 requirements -->/--><!-- End Hadoop 2 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- HDP 2.2 requirements -->/<!-- HDP 2.2 requirements --><!--/' \
-      -e 's/<!-- End HDP 2.2 requirements -->/--><!-- End HDP 2.2 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- IOP 4.1 requirements -->/<!-- IOP 4.1 requirements --><!--/' \
-      -e 's/<!-- End IOP 4.1 requirements -->/--><!-- End IOP 4.1 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-  elif [[ "${HADOOP_VERSION}" == "HDP2.2" ]]; then
-    sed -e 's/<!-- Hadoop 2 requirements -->/<!-- Hadoop 2 requirements --><!--/' \
-      -e 's/<!-- End Hadoop 2 requirements -->/--><!-- End Hadoop 2 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- HDP 2.0 requirements -->/<!-- HDP 2.0 requirements --><!--/' \
-      -e 's/<!-- End HDP 2.0 requirements -->/--><!-- End HDP 2.0 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- IOP 4.1 requirements -->/<!-- IOP 4.1 requirements --><!--/' \
-      -e 's/<!-- End IOP 4.1 requirements -->/--><!-- End IOP 4.1 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-  elif [[ "${HADOOP_VERSION}" == "IOP4.1" ]]; then
-    sed -e 's/<!-- Hadoop 2 requirements -->/<!-- Hadoop 2 requirements --><!--/' \
-      -e 's/<!-- End Hadoop 2 requirements -->/--><!-- End Hadoop 2 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- HDP 2.0 requirements -->/<!-- HDP 2.0 requirements --><!--/' \
-      -e 's/<!-- End HDP 2.0 requirements -->/--><!-- End HDP 2.0 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-    sed -e 's/<!-- HDP 2.2 requirements -->/<!-- HDP 2.2 requirements --><!--/' \
-      -e 's/<!-- End HDP 2.2 requirements -->/--><!-- End HDP 2.2 requirements -->/' \
-      "${CONF_DIR}/$ACCUMULO_SITE" > temp
-    mv temp "${CONF_DIR}/$ACCUMULO_SITE"
-  fi
-
-  #Additional setup steps for native configuration.
-  if [[ ${TYPE} == native ]]; then
-    if [[ $(uname) == Linux ]]; then
-      if [[ -z $HADOOP_PREFIX ]]; then
-        echo "WARNING: HADOOP_PREFIX not set, cannot automatically configure LD_LIBRARY_PATH to include Hadoop native libraries"
-      else
-        NATIVE_LIB=$(readlink -ef "$(dirname "$(for x in $(find "$HADOOP_PREFIX" -name libhadoop.so); do ld "$x" 2>/dev/null && echo "$x" && break; done)" 2>>/dev/null)" 2>>/dev/null)
-        if [[ -z $NATIVE_LIB ]]; then
-          echo -e "WARNING: The Hadoop native libraries could not be found for your sytem in: $HADOOP_PREFIX"
-        else
-          sed "/# Should the monitor/ i export LD_LIBRARY_PATH=${NATIVE_LIB}:\${LD_LIBRARY_PATH}" "${CONF_DIR}/$ACCUMULO_ENV" > temp
-          mv temp "${CONF_DIR}/$ACCUMULO_ENV"
-          echo -e "Added ${NATIVE_LIB} to the LD_LIBRARY_PATH"
-        fi
-      fi
-    fi
-    echo -e "Please remember to compile the Accumulo native libraries using the command 'accumulo-util build-native' and to set the LD_LIBRARY_PATH variable in the ${CONF_DIR}/accumulo-env.sh if needed."
-  fi
-
-  echo "Setup complete"
 }
 
 function build_native() {
@@ -516,9 +135,15 @@ function gen_monitor_cert() {
 }
 
 function load_jars_hdfs() {
-  if [ -z "$HADOOP_PREFIX" ]; then
-     echo "HADOOP_PREFIX is not set!"
-     exit 1
+
+  if [ -x "$HADOOP_PREFIX/bin/hadoop" ]; then
+    HADOOP="$HADOOP_PREFIX/bin/hadoop"
+  else
+    HADOOP=$(which hadoop)
+  fi
+  if [ ! -x "$HADOOP" ]; then
+    echo "Could not find 'hadoop' command. Please set hadoop on your PATH or set HADOOP_PREFIX"
+    exit 1
   fi
 
   # Find the system context directory in HDFS
@@ -540,9 +165,9 @@ function load_jars_hdfs() {
   fi
 
   # Create the system context directy in HDFS if it does not exist
-  "$HADOOP_PREFIX/bin/hadoop" fs -ls "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
+  "$HADOOP" fs -ls "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
   if [[ $? != 0 ]]; then
-    "$HADOOP_PREFIX/bin/hadoop" fs -mkdir "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
+    "$HADOOP" fs -mkdir "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
     if [[ $? != 0 ]]; then
       echo "Unable to create classpath directory at $SYSTEM_CONTEXT_HDFS_DIR"
       exit 1
@@ -558,22 +183,27 @@ function load_jars_hdfs() {
   (( REP < 3 )) && REP=3
 
   # Copy all jars in lib to the system context directory
-  "$HADOOP_PREFIX/bin/hadoop" fs -moveFromLocal "$lib"/*.jar "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
-  "$HADOOP_PREFIX/bin/hadoop" fs -setrep -R $REP "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
+  "$HADOOP" fs -moveFromLocal "$lib"/*.jar "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
+  "$HADOOP" fs -setrep -R $REP "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
 
   # We need some of the jars in lib, copy them back out and remove them from the system context dir
-  "$HADOOP_PREFIX/bin/hadoop" fs -copyToLocal "$SYSTEM_CONTEXT_HDFS_DIR/commons-vfs2.jar" "$lib/."  > /dev/null
-  "$HADOOP_PREFIX/bin/hadoop" fs -rm "$SYSTEM_CONTEXT_HDFS_DIR/commons-vfs2.jar"  > /dev/null
-  "$HADOOP_PREFIX/bin/hadoop" fs -copyToLocal "$SYSTEM_CONTEXT_HDFS_DIR/accumulo-start.jar" "$lib/."  > /dev/null
-  "$HADOOP_PREFIX/bin/hadoop" fs -rm "$SYSTEM_CONTEXT_HDFS_DIR/accumulo-start.jar"  > /dev/null
-  "$HADOOP_PREFIX/bin/hadoop" fs -copyToLocal "$SYSTEM_CONTEXT_HDFS_DIR/slf4j*.jar" "$lib/."  > /dev/null
-  "$HADOOP_PREFIX/bin/hadoop" fs -rm "$SYSTEM_CONTEXT_HDFS_DIR/slf4j*.jar"  > /dev/null
+  "$HADOOP" fs -copyToLocal "$SYSTEM_CONTEXT_HDFS_DIR/commons-vfs2.jar" "$lib/."  > /dev/null
+  "$HADOOP" fs -rm "$SYSTEM_CONTEXT_HDFS_DIR/commons-vfs2.jar"  > /dev/null
+  "$HADOOP" fs -copyToLocal "$SYSTEM_CONTEXT_HDFS_DIR/accumulo-start.jar" "$lib/."  > /dev/null
+  "$HADOOP" fs -rm "$SYSTEM_CONTEXT_HDFS_DIR/accumulo-start.jar"  > /dev/null
+  "$HADOOP" fs -copyToLocal "$SYSTEM_CONTEXT_HDFS_DIR/slf4j*.jar" "$lib/."  > /dev/null
+  "$HADOOP" fs -rm "$SYSTEM_CONTEXT_HDFS_DIR/slf4j*.jar"  > /dev/null
 }
 
 function hadoop_jar() {
-  if [ -z "$HADOOP_PREFIX" ]; then
-     echo "HADOOP_PREFIX must be set!"
-     exit 1
+  if [ -x "$HADOOP_PREFIX/bin/hadoop" ]; then
+    HADOOP="$HADOOP_PREFIX/bin/hadoop"
+  else
+    HADOOP=$(which hadoop)
+  fi
+  if [ ! -x "$HADOOP" ]; then
+    echo "Could not find 'hadoop' command. Please set hadoop on your PATH or set HADOOP_PREFIX"
+    exit 1
   fi
   if [ -z "$ZOOKEEPER_HOME" ]; then
      echo "ZOOKEEPER_HOME must be set!"
@@ -628,11 +258,7 @@ function hadoop_jar() {
      exit 1
   fi
 
-  #echo USERJARS=$USERJARS
-  #echo CLASSNAME=$CLASSNAME
-  #echo HADOOP_CLASSPATH=$HADOOP_CLASSPATH
-  #echo exec "$HADOOP_PREFIX/bin/hadoop" jar "$TOOLJAR" "$CLASSNAME" -libjars \"$LIB_JARS\" $ARGS
-  exec "$HADOOP_PREFIX/bin/hadoop" jar "$TOOLJAR" "$CLASSNAME" -libjars "$LIB_JARS" "$@"
+  exec "$HADOOP" jar "$TOOLJAR" "$CLASSNAME" -libjars "$LIB_JARS" "$@"
 }
 
 function main() {
@@ -648,9 +274,6 @@ function main() {
   lib="${basedir}/lib"
 
   case "$1" in
-    create-config)
-      create_config "${@:2}"
-      ;;
     build-native)
       build_native "${@:2}"
       ;;
