ACCUMULO-3952 Verify the log4j jar was found in the Hadoop installation.
The `find` command may fail (personally, ran into this when the cwd
was a directory that was not readable by the user). We miss this
and blindly proceed. Presently, Accumulo processes will fail miserably
when log4j isn't present. Since the user _may_ add a log4j jar to the
CLASSPATH, we avoid erroring out when CLASSPATH is non-empty

Conflicts:
	assemble/bin/accumulo

diff --git a/assemble/bin/accumulo b/assemble/bin/accumulo
--- a/assemble/bin/accumulo
+++ b/assemble/bin/accumulo
@@ -117,6 +117,14 @@ esac
 
 XML_FILES="${ACCUMULO_CONF_DIR}"
 LOG4J_JAR=$(find -H "${HADOOP_PREFIX}/lib" "${HADOOP_PREFIX}"/share/hadoop/common/lib -name 'log4j*.jar' -print 2>/dev/null | head -1)
+
+# The `find` command could fail for environmental reasons or bad configuration
+# Avoid trying to run Accumulo when we can't find the jar
+if [ -z "${LOG4J_JAR}" ]; then
+   echo "Could not locate Log4j jar in Hadoop installation at ${HADOOP_PREFIX}"
+   exit 1
+fi
+
 CLASSPATH="${XML_FILES}:${START_JAR}:${LOG4J_JAR}"
 
 if [ -z "${JAVA_HOME}" -o ! -d "${JAVA_HOME}" ]; then
