adds prune command to accumulo-cluster
As the cluster.yaml file is changed it can leave extra server process
around. The accumulo-cluster script currently does not have a way to
look for extra servers processes, it only operates on what is specified
in the cluster.yaml file.

This commit adds the ability to remove servers that exist in zookeeper
but would not be expected based on the cluster.yaml and current pid
files.

Co-authored-by: Daniel Roberts ddanielr <ddanielr@gmail.com>

diff --git a/assemble/bin/accumulo-cluster b/assemble/bin/accumulo-cluster
--- a/assemble/bin/accumulo-cluster
+++ b/assemble/bin/accumulo-cluster
@@ -54,6 +54,7 @@ $(cyan Commands):
   $(green stop)                       Stops Accumulo cluster services
   $(green restart)                    Restarts Accumulo cluster services
   $(green kill)                       Kills Accumulo cluster services
+  $(green prune)                      Reomves zookeeper locks of extra processes
 
   $(cyan Deprecated commands):
     $(green start-non-tservers)       $(yellow Deprecated). Alias for "start --no-tservers"
@@ -73,6 +74,8 @@ $(cyan Examples):
   $(purple 'accumulo-cluster start --sservers=group1')            $(blue '# start all group1 sservers')
   $(purple 'accumulo-cluster start --sservers="group1 group2"')   $(blue '# start all group1 and group2 sservers')
   $(purple 'accumulo-cluster start --local --manager --tservers') $(blue '# Start the local manager and local tservers')
+  $(purple 'accumulo-cluster prune --compactors')                 $(blue '# prune all extra compactors across all groups')
+  $(purple 'accumulo-cluster prune --compactors="group1"')        $(blue '# prune extra compactors running in group1')
 
 EOF
 }
@@ -324,8 +327,14 @@ function parse_config() {
     exit 1
   fi
 
-  trap 'rm -f "$CONFIG_FILE"' EXIT
-  CONFIG_FILE=$(mktemp --tmpdir "ClusterConfigParser-XXXXXXXX.out") || exit 1
+  AC_TMP_DIR=$(mktemp -t -d "accumulo-cluster-XXXXXXXX") || exit 1
+  if isDebug; then
+    echo "$(blue DEBUG): Temporary files for this run are in $AC_TMP_DIR"
+  else
+    trap 'rm -rf -- "$AC_TMP_DIR"' EXIT
+  fi
+
+  CONFIG_FILE="$AC_TMP_DIR/ClusterConfigParser.out"
   "$accumulo_cmd" org.apache.accumulo.core.conf.cluster.ClusterConfigParser "$conf/cluster.yaml" "$CONFIG_FILE" || parse_fail
   #shellcheck source=/dev/null
   . "$CONFIG_FILE"
@@ -646,10 +655,170 @@ function control_services() {
   if [[ $ARG_LOCAL == 0 && $ARG_ALL == 1 && ($operation == "stop" || $operation == "kill") ]]; then
     if ! isDebug; then
       echo "Cleaning all server entries in ZooKeeper"
-      "$accumulo_cmd" org.apache.accumulo.server.util.ZooZap -manager -tservers -compaction-coordinators -compactors -sservers
+      "$accumulo_cmd" org.apache.accumulo.server.util.ZooZap -manager -tservers -compaction-coordinators -compactors -sservers --gc --monitor
     fi
   fi
 
+}
+
+function prune_group() {
+  local service_type=$1
+  local group=$2
+  local expectedCount=$3
+  declare -a hosts
+  read -r -a hosts <<<"$4"
+
+  if isDebug; then
+    echo "$(blue DEBUG) starting prune for service:$service_type group:$group expected:$expectedCount"
+  fi
+
+  if [ -z ${AC_TMP_DIR+x} ]; then
+    echo "$(red ERROR): AC_TMP_DIR is not set"
+    exit 1
+  fi
+  local exclude_file="$AC_TMP_DIR/accumulo-zoozap-exclude-$service_type-$group.txt"
+  touch "$exclude_file"
+
+  # Determine the host:ports known by the accumulo cluster script, these should be kept
+  for host in "${hosts[@]}"; do
+    "${SSH[@]}" "$host" bash -c "'$bin/accumulo-service $service_type list'" | grep -E "^[a-zA-Z0-9]+_${group}_[0-9]+" | head -n "$expectedCount" | awk '{print $3}' | tr ',' '\n' | awk '{print "'"$host"':" $1}' >>"$exclude_file"
+  done
+
+  local lockTypeOpt
+  case $service_type in
+    manager)
+      lockTypeOpt="-manager"
+      ;;
+    compaction-coordinator)
+      lockTypeOpt="-compaction-coordinators"
+      ;;
+    compactor)
+      lockTypeOpt="-compactors"
+      ;;
+    tserver)
+      lockTypeOpt="-tservers"
+      ;;
+    sserver)
+      lockTypeOpt="-sservers"
+      ;;
+    gc)
+      lockTypeOpt="--gc"
+      ;;
+    monitor)
+      lockTypeOpt="--monitor"
+      ;;
+    *)
+      echo "Prune does not support $service_type"
+      exit 1
+      ;;
+  esac
+
+  if isDebug; then
+    "$accumulo_cmd" org.apache.accumulo.server.util.ZooZap "$lockTypeOpt" -verbose --include-groups "$group" --exclude-host-ports "$exclude_file" --dry-run
+  else
+    "$accumulo_cmd" org.apache.accumulo.server.util.ZooZap "$lockTypeOpt" -verbose --include-groups "$group" --exclude-host-ports "$exclude_file"
+  fi
+}
+
+# Kills extra server processes that are not needed according to the
+# cluster.yaml file.  Conceptually this code is trying to reconcile the
+# following three sets of servers.
+#
+#  1. The notional goal set of servers specified by cluster.yaml
+#  2. The set of servers processes seen in zookeeper
+#  3. The set of server processes known to the accumulo-cluster script.  This
+#     is derived from pid files on hosts in set 1.
+#
+# This function attempts to find extra servers in set 2 that are not specified
+# by set 1.  When it does find extra servers it removes their zookeeper locks
+# avoiding removing locks of servers in set 3. The following are different
+# situations the code will see and handle.
+#
+#  * When a host is not cluster.yaml but has some processes listed in
+#    zookeeper.  For this case all of the process with that host can be killed.
+#  * When a resource group is not in cluster.yaml but has some processes listed
+#    in zookeeper.  For this case all of the processes with that resource group
+#    can be killed.
+#  * When a host is in cluster.yaml with a target of 3 processes but has 6
+#    processes listed in zookeeper.  For this case want to kill 3 processes that
+#    do not have pid files on the host.
+#
+function prune() {
+  if [[ $ARG_LOCAL == 1 ]]; then
+    # Currently the code is structured to remove all extra servers in a single resource group.  Finer granularity is not supported.
+    echo "$(red ERROR): Prune does not support running locally"
+    exit 1
+  fi
+
+  if [[ -z ${AC_TMP_DIR+x} ]]; then
+    echo "AC_TMP_DIR is not set"
+    exit 1
+  fi
+  local service_json="$AC_TMP_DIR/accumulo-service.json"
+  "$accumulo_cmd" admin serviceStatus --json >"$service_json" 2>/dev/null || exit 1
+
+  local var_name
+  local hosts
+  declare -a groups
+
+  local manager
+  if [[ $ARG_ALL == 1 || $ARG_MANAGER == 1 ]]; then
+    prune_group "manager" "default" "1" "$MANAGER_HOSTS"
+  fi
+
+  if [[ $ARG_ALL == 1 || $ARG_GC == 1 ]]; then
+    prune_group "gc" "default" "1" "$GC_HOSTS"
+  fi
+
+  if [[ $ARG_ALL == 1 || $ARG_MONITOR == 1 ]]; then
+    prune_group "monitor" "default" "1" "$MONITOR_HOSTS"
+  fi
+
+  if [[ $ARG_ALL == 1 || $ARG_COORDINATOR == 1 ]]; then
+    prune_group "compaction-coordinator" "default" "1" "$COORDINATOR_HOSTS"
+  fi
+
+  if [[ $ARG_ALL == 1 || $ARG_TSERVER == 1 ]]; then
+    #TODO in main need to adapt to having RGs for tservers
+    prune_group "tserver" "default" "$TSERVERS_PER_HOST_default" "$TSERVER_HOSTS_default"
+  fi
+
+  if [[ $ARG_ALL == 1 || $ARG_SSERVER == 1 ]]; then
+    groups=()
+    if [[ -n $ARG_SSERVER_GROUP ]]; then
+      read -r -a groups <<<"$ARG_SSERVER_GROUP"
+    else
+      # find all groups known in zookeeper, this will allow pruning entire groups that do not even exists in cluster.yaml
+      readarray -t groups < <(jq -r ".summaries.S_SERVER.resourceGroups | .[] " "$service_json")
+    fi
+
+    for group in "${groups[@]}"; do
+      var_name="SSERVERS_PER_HOST_$group"
+      local expected=${!var_name:-0}
+
+      hosts="SSERVER_HOSTS_$group"
+      prune_group "sserver" "$group" "$expected" "${!hosts}"
+    done
+
+  fi
+
+  if [[ $ARG_ALL == 1 || $ARG_COMPACTOR == 1 ]]; then
+    groups=()
+    if [[ -n $ARG_COMPACTOR_GROUP ]]; then
+      read -r -a groups <<<"$ARG_COMPACTOR_GROUP"
+    else
+      # find all groups known in zookeeper, this will allow pruning entire groups that do not even exists in cluster.yaml
+      readarray -t groups < <(jq -r ".summaries.COMPACTOR.resourceGroups | .[] " "$service_json")
+    fi
+
+    for group in "${groups[@]}"; do
+      var_name="COMPACTORS_PER_HOST_$group"
+      local expected=${!var_name:-0}
+
+      hosts="COMPACTOR_HOSTS_$group"
+      prune_group "compactor" "$group" "$expected" "${!hosts}"
+    done
+  fi
 }
 
 function main() {
@@ -757,6 +926,10 @@ EOF
       ARG_LOCAL=1
       control_services stop
       control_services kill
+      ;;
+    prune)
+      parse_config
+      prune
       ;;
     start-non-tservers)
       echo "'$ARG_CMD' is deprecated. Please specify the servers you wish to start instead"
