Fix accumulo-util script
* Fix variable name typo for native_tarballs
* Fix issues identified by shellcheck

diff --git a/assemble/bin/accumulo-util b/assemble/bin/accumulo-util
--- a/assemble/bin/accumulo-util
+++ b/assemble/bin/accumulo-util
@@ -31,14 +31,14 @@ EOF
 
 function build_native() {
   final_native_target="$basedir/lib/native"
-  if [ -f "$final_native_target/libaccumulo.so" -o -f "$final_native_target/libaccumulo.dylib" ]; then
+  if [[ -f "$final_native_target/libaccumulo.so" ]] || [[ -f "$final_native_target/libaccumulo.dylib" ]]; then
     echo "Accumulo native library already exists in $final_native_target"
     exit 0
   fi
 
   native_tarballs=("$basedir"/lib/accumulo-native-*.tar.gz)
-  if (( ${#logfiles[@]} > 1 )); then
-    echo "Found multiple native tar.gz files ${native_tarballs[*]}"
+  if (( ${#native_tarballs[@]} > 1 )); then
+    echo "Found multiple native tar.gz files: ${native_tarballs[*]}"
     exit 1
   fi
 
@@ -154,10 +154,8 @@ function load_jars_hdfs() {
   fi
 
   # Create the system context directy in HDFS if it does not exist
-  "$HADOOP" fs -ls "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
-  if [[ $? != 0 ]]; then
-    "$HADOOP" fs -mkdir "$SYSTEM_CONTEXT_HDFS_DIR"  > /dev/null
-    if [[ $? != 0 ]]; then
+  if ! "$HADOOP" fs -ls "$SYSTEM_CONTEXT_HDFS_DIR" > /dev/null; then
+    if ! "$HADOOP" fs -mkdir "$SYSTEM_CONTEXT_HDFS_DIR" > /dev/null; then
       echo "Unable to create classpath directory at $SYSTEM_CONTEXT_HDFS_DIR"
       exit 1
     fi
@@ -165,7 +163,7 @@ function load_jars_hdfs() {
 
   # Replicate to all tservers to avoid network contention on startup
   TSERVERS=${conf}/tservers
-  NUM_TSERVERS=$(egrep -v '(^#|^\s*$)' "$TSERVERS" | wc -l)
+  NUM_TSERVERS=$(grep -E -c -v '(^#|^\s*$)' "$TSERVERS")
 
   #let each datanode service around 50 clients
   REP=$(( NUM_TSERVERS / 50 ))
@@ -215,16 +213,16 @@ function hadoop_jar() {
 
   USERJARS=" "
   for arg in "$@"; do
-      if [ "$arg" != "-libjars" -a -z "$TOOLJAR" ]; then
+      if [[ "$arg" != "-libjars" ]] && [[ -z "$TOOLJAR" ]]; then
         TOOLJAR="$arg"
         shift
-     elif [ "$arg" != "-libjars" -a -z "$CLASSNAME" ]; then
+     elif [[ "$arg" != "-libjars" ]] && [[ -z "$CLASSNAME" ]]; then
         CLASSNAME="$arg"
         shift
-     elif [ -z "$USERJARS" ]; then
+     elif [[ -z "$USERJARS" ]]; then
         USERJARS=$(echo "$arg" | tr "," " ")
         shift
-     elif [ "$arg" = "-libjars" ]; then
+     elif [[ "$arg" = "-libjars" ]]; then
         USERJARS=""
         shift
      else
@@ -275,7 +273,7 @@ function main() {
       load_jars_hdfs
       ;;
     *)
-      echo -e "'$1' is an invalid <command>\n"
+      echo -e "'$1' is an invalid <command>\\n"
       print_usage 1>&2
       exit 1
       ;;
