Run shfmt and shellcheck on scripts (#2677)
* Run shfmt to format scripts
* Run shellcheck to check all scripts for bugs
* Add automated check for shfmt and shellcheck during CI

diff --git a/assemble/bin/accumulo-util b/assemble/bin/accumulo-util
--- a/assemble/bin/accumulo-util
+++ b/assemble/bin/accumulo-util
@@ -39,7 +39,7 @@ function build_native() {
   fi
 
   native_tarballs=("$basedir"/lib/accumulo-native-*.tar.gz)
-  if (( ${#native_tarballs[@]} > 1 )); then
+  if ((${#native_tarballs[@]} > 1)); then
     echo "Found multiple native tar.gz files: ${native_tarballs[*]}"
     exit 1
   fi
@@ -56,10 +56,9 @@ function build_native() {
   TMP_DIR=$(mktemp -d /tmp/accumulo-native.XXXXXX) || exit 1
 
   # Unpack the tarball to our temp directory
-  if ! tar xf "${native_tarballs[0]}" -C "${TMP_DIR}"
-  then
-      echo "Failed to unpack native tarball to ${TMP_DIR}"
-      exit 1
+  if ! tar xf "${native_tarballs[0]}" -C "${TMP_DIR}"; then
+    echo "Failed to unpack native tarball to ${TMP_DIR}"
+    exit 1
   fi
 
   # Move to the first (only) directory in our unpacked tarball
@@ -69,7 +68,10 @@ function build_native() {
 
   # Make the native library
   export USERFLAGS="$*"
-  make || { echo 'Make failed!'; exit 1; }
+  make || {
+    echo 'Make failed!'
+    exit 1
+  }
 
   # "install" the artifact
   cp libaccumulo.* "${final_native_target}" || exit 1
@@ -81,43 +83,43 @@ function build_native() {
 }
 
 function gen_monitor_cert() {
-  if [[ -z "$JAVA_HOME" || ! -d "$JAVA_HOME" ]]; then
+  if [[ -z $JAVA_HOME || ! -d $JAVA_HOME ]]; then
     echo "JAVA_HOME=${JAVA_HOME} must be set and exist"
     exit 1
   fi
 
   ALIAS="default"
-  KEYPASS=$(LC_CTYPE=C tr -dc '#-~' < /dev/urandom | tr -d '<>&' | head -c 20)
-  STOREPASS=$(LC_CTYPE=C tr -dc '#-~' < /dev/urandom | tr -d '<>&' | head -c 20)
+  KEYPASS=$(LC_CTYPE=C tr -dc '#-~' </dev/urandom | tr -d '<>&' | head -c 20)
+  STOREPASS=$(LC_CTYPE=C tr -dc '#-~' </dev/urandom | tr -d '<>&' | head -c 20)
   KEYSTOREPATH="${conf}/keystore.jks"
   TRUSTSTOREPATH="${conf}/cacerts.jks"
   CERTPATH="${conf}/server.cer"
 
-  if [[ -e "$KEYSTOREPATH" ]]; then
-     rm -i "$KEYSTOREPATH"
-     if [[ -e "$KEYSTOREPATH" ]]; then
-        echo "KeyStore already exists, exiting"
-        exit 1
-     fi
+  if [[ -e $KEYSTOREPATH ]]; then
+    rm -i "$KEYSTOREPATH"
+    if [[ -e $KEYSTOREPATH ]]; then
+      echo "KeyStore already exists, exiting"
+      exit 1
+    fi
   fi
-  if [[ -e "$TRUSTSTOREPATH" ]]; then
-     rm -i "$TRUSTSTOREPATH"
-     if [[ -e "$TRUSTSTOREPATH" ]]; then
-        echo "TrustStore already exists, exiting"
-        exit 2
-     fi
+  if [[ -e $TRUSTSTOREPATH ]]; then
+    rm -i "$TRUSTSTOREPATH"
+    if [[ -e $TRUSTSTOREPATH ]]; then
+      echo "TrustStore already exists, exiting"
+      exit 2
+    fi
   fi
-  if [[ -e "$CERTPATH" ]]; then
-     rm -i "$CERTPATH"
-     if [[ -e "$CERTPATH" ]]; then
-        echo "Certificate already exists, exiting"
-        exit 3
+  if [[ -e $CERTPATH ]]; then
+    rm -i "$CERTPATH"
+    if [[ -e $CERTPATH ]]; then
+      echo "Certificate already exists, exiting"
+      exit 3
     fi
   fi
 
   "${JAVA_HOME}/bin/keytool" -genkey -alias "$ALIAS" -keyalg RSA -keypass "$KEYPASS" -storepass "$KEYPASS" -keystore "$KEYSTOREPATH"
   "${JAVA_HOME}/bin/keytool" -export -alias "$ALIAS" -storepass "$KEYPASS" -file "$CERTPATH" -keystore "$KEYSTOREPATH"
-  "${JAVA_HOME}/bin/keytool" -import -v -trustcacerts -alias "$ALIAS" -file "$CERTPATH" -keystore "$TRUSTSTOREPATH" -storepass "$STOREPASS" <<< "yes"
+  "${JAVA_HOME}/bin/keytool" -import -v -trustcacerts -alias "$ALIAS" -file "$CERTPATH" -keystore "$TRUSTSTOREPATH" -storepass "$STOREPASS" <<<"yes"
 
   echo
   echo "keystore and truststore generated.  now add the following to accumulo.properties:"
@@ -132,14 +134,16 @@ function gen_monitor_cert() {
 function main() {
   SOURCE="${BASH_SOURCE[0]}"
   while [ -h "${SOURCE}" ]; do
-     bin="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"
-     SOURCE="$(readlink "${SOURCE}")"
-     [[ "${SOURCE}" != /* ]] && SOURCE="${bin}/${SOURCE}"
+    bin="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
+    SOURCE="$(readlink "${SOURCE}")"
+    [[ ${SOURCE} != /* ]] && SOURCE="${bin}/${SOURCE}"
   done
-  bin="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"
-  basedir=$( cd -P "${bin}"/.. && pwd )
-  conf="${ACCUMULO_CONF_DIR:-${basedir}/conf}"
-  lib="${basedir}/lib"
+  bin="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
+  export bin
+  basedir=$(cd -P "${bin}"/.. && pwd)
+  export basedir
+  export conf="${ACCUMULO_CONF_DIR:-${basedir}/conf}"
+  export lib="${basedir}/lib"
 
   case "$1" in
     build-native)
